<a href="https://colab.research.google.com/github/Putri-Hasinatuzzafira/SQL_Bigquery-DQLab/blob/main/01_select_limit_orderby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <b><span style='color:#0B2F9F'>Pengantar</span></b>

Dalam analisis data, langkah awal yang penting adalah mengambil, membatasi, dan mengurutkan informasi dari sumber data agar hasil yang diperoleh relevan dan mudah dipahami. Kemampuan untuk menampilkan data sesuai kebutuhan, hanya pada bagian yang diperlukan, serta menyusunnya dengan urutan yang tepat, menjadi dasar dalam proses eksplorasi dan pengolahan data. Dengan pemahaman konsep ini, seorang analis dapat bekerja lebih efisien dalam menemukan pola, menjawab pertanyaan bisnis, dan menyajikan insight yang akurat.

# <b><span style='color:#0B2F9F'>Set up</span></b>

Dibutuhkan proses autentikasi dari Google Colab ke Google Big Query. Ikuti langkah berikut https://drive.google.com/file/d/1gW8alZ_PrvcrsieqWCHOR4ssLI_25BRc/view untuk detail step-by-step nya

In [31]:
# Import library yang dibutuhkan
from google.colab import auth, data_table
from google.cloud import bigquery
from pandas_gbq import to_gbq

# Proses autentikasi akun
auth.authenticate_user()
print('Authenticated')

Authenticated

In [32]:
# Buat BigQuery client
project_id = 'dqlab-putri512'
client = bigquery.Client(project = project_id)

# <b><span style='color:#0B2F9F'>Latar Belakang</span></b>

Di sebuah sudut kota Jakarta, telah didirikan sebuah restoran pizza bernama Plato’s Pizza. Selama satu tahun terakhir, telah dilakukan pencatatan atas setiap transaksi yang terjadi. Mulai dari pemesanan menu hingga pembayaran pelanggan. Banyak data telah dikumpulkan dan dicatat. Namun, belum dilakukan pemanfaatan optimal terhadap informasi yang tersedia. Pemilik restoran menginginkan agar data ini dapat dianalisis guna menemukan ruang untuk perbaikan dan melakukan efisiensi operasional sehingga diharapkan dapat meningkatkan penjualan pizza, menekan biaya operasional dan meningkatkan customer experience

<a id="A"></a>
# <b>A. <span style='color:#0B2F9F'><code>SELECT</code></span></b>

Perintah `SELECT` bertujuan untuk mengambil dan menampilkan data dari tabel di database. Ini penting untuk analisis karena saat menganalisa data perlu mengakses data yang relevan untuk dianalisis seperti mengidentifikasi pola, tren, dan informasi penting lainnya.

<a id="A.1."></a>
## <b>A.1. <span style='color:#0B2F9F'>Menampilkan Semua Data pada Satu Tabel</span></b>

Untuk dapat menampilkan semua isi (data) pada sebuah tabel, eksekusi perintah

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL-Select1.png" width="50%">

Dalam perintah `SELECT`, tanda bintang (*) digunakan untuk memilih semua kolom dari tabel yang disebutkan. Cara ini merupakan cara cepat untuk mengambil seluruh data tanpa perlu menyebutkan nama-nama kolom satu per satu.

<i>docs : <a href="https://dev.mysql.com/doc/refman/8.4/en/selecting-all.html">https://dev.mysql.com/doc/refman/8.4/en/selecting-all.html</a></i>

#### <i><b><span style='color:#55679C'>Quest</span> : Management ingin mengetahui seluruh data transaksi pada DQPizza, sehingga tampilkan semua data pada tabel orders!</b></i>

In [33]:
%%bigquery --project {project_id} --verbose

-- Tampilkan semua data pada tabel orders
SELECT * FROM dqlab-putri512.dq_pizza.orders

Executing query with job ID: 5e971326-227f-49eb-a355-47922ad60011
Query executing: 1.37s
Job ID 5e971326-227f-49eb-a355-47922ad60011 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail
0,TRX000026,CUST006333,EMP000208,01/01/2024,14:54:26,15:23:02,0,None
1,TRX000037,CUST003319,EMP000208,01/01/2024,16:56:09,17:18:48,0,None
2,TRX000057,CUST008422,EMP000208,01/01/2024,19:10:51,19:30:38,0,None
3,TRX000077,CUST001979,EMP000208,01/02/2024,12:22:46,12:41:29,0,None
4,TRX000087,CUST004837,EMP000208,01/02/2024,14:01:02,14:29:46,0,None
...,...,...,...,...,...,...,...,...
21345,TRX009714,CUST004609,EMP000756,06/12/2024,15:32:54,15:52:27,1,Wrong pizza size
21346,TRX011127,CUST003549,EMP000756,07/05/2024,12:49:09,13:03:28,1,Wrong pizza size
21347,TRX011178,CUST008535,EMP000756,07/06/2024,13:09:22,13:28:47,1,Wrong pizza size
21348,TRX012098,CUST001979,EMP000756,07/21/2024,18:11:15,18:33:56,1,Wrong pizza size
21349,TRX019645,CUST001120,EMP000756,11/30/2024,17:07:35,17:34:36,1,Wrong pizza size

<a id="A.2."></a>
## <b>A.2. <span style='color:#0B2F9F'>Menampilkan Kolom Tertentu pada Satu Tabel</span></b>

Untuk dapat menampilkan isi data pada kolom tertentu pada sebuah tabel, eksekusi perintah

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL-Select2.png" width="50%">

Gunakan tanda koma untuk mendaftarkan nama kolom yang ingin ditampilkan. Kolom yang disebutkan pertama kali akan ditampilkan paling kiri begitu juga dengan kolom kedua hingga kolom terakhir.

<i>docs : <a href="https://dev.mysql.com/doc/refman/8.4/en/selecting-columns.html">https://dev.mysql.com/doc/refman/8.4/en/selecting-columns.html</a></i>

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan kolom order_id, customer_id dan order_date pada tabel orders!</b></i>

In [34]:
%%bigquery --project {project_id} --verbose

-- Tampilkan kolom order_id, customer_id dan order_date pada tabel orders
SELECT order_id, customer_id, order_date FROM dqlab-putri512.dq_pizza.orders

Executing query with job ID: 065d121e-cd8b-49f2-87d1-01c561491b47
Query executing: 1.26s
Job ID 065d121e-cd8b-49f2-87d1-01c561491b47 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

        order_id customer_id  order_date
0      TRX000208  CUST009755  01/04/2024
1      TRX000218  CUST008987  01/04/2024
2      TRX000387  CUST004307  01/07/2024
3      TRX000403  CUST002835  01/07/2024
4      TRX000502  CUST003147  01/08/2024
...          ...         ...         ...
21345  TRX009812  CUST009740  06/13/2024
21346  TRX020835  CUST009740  12/20/2024
21347  TRX014036  CUST009740  08/22/2024
21348  TRX005932  CUST009740  04/10/2024
21349  TRX020194  CUST009740  12/09/2024

[21350 rows x 3 columns]

<a id="A.3."></a>
## <b>A.3. <span style='color:#0B2F9F'>Mengubah Penyebutan Nama Kolom pada Satu Tabel</span></b>

Terkadang perlu untuk memberi nama lain pada saat data ditampilkan untuk mempermudah pembacaan atau tujuan lainnya. Untuk mengubah nama sementara yang diberikan kepada kolom atau tabel dalam query bisa menggunakan perintah `AS` atau biasa disebut Alias. Untuk dapat mengubah nama kolom sementara pada sebuah tabel, eksekusi perintah

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL-Select3.png" width="50%">

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan kolom order_id, customer_id, order_date dan is_complain pada tabel orders namun ubah penamaan is_complain pada output menjadi is_customer_complain agar lebih jelas</b></i>

In [35]:
%%bigquery --project {project_id} --verbose

-- Tampilkan kolom order_id, customer_id, order_date dan is_complain pada tabel orders
-- namun ubah penamaan is_complain pada output menjadi is_customer_complain
SELECT
  order_id,
  customer_id,
  order_date,
  is_complain AS is_customer_complain
FROM dqlab-putri512.dq_pizza.orders

Executing query with job ID: c39685dd-7e74-4b39-b4c8-71a59cdcbd23
Query executing: 1.26s
Job ID c39685dd-7e74-4b39-b4c8-71a59cdcbd23 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

        order_id customer_id  order_date  is_customer_complain
0      TRX000026  CUST006333  01/01/2024                     0
1      TRX000037  CUST003319  01/01/2024                     0
2      TRX000057  CUST008422  01/01/2024                     0
3      TRX000077  CUST001979  01/02/2024                     0
4      TRX000087  CUST004837  01/02/2024                     0
...          ...         ...         ...                   ...
21345  TRX009714  CUST004609  06/12/2024                     1
21346  TRX011127  CUST003549  07/05/2024                     1
21347  TRX011178  CUST008535  07/06/2024                     1
21348  TRX012098  CUST001979  07/21/2024                     1
21349  TRX019645  CUST001120  11/30/2024                     1

[21350 rows x 4 columns]

<a id="B"></a>
# <b>B. <span style='color:#E1B12D'><code>DISTINCT</code></span></b>

Perintah `DISTINCT` dalam SQL digunakan untuk menghapus duplikasi dalam hasil query. Dengan `DISTINCT`, dapat dipastikan bahwa setiap baris dalam hasil query unik dan tidak ada baris yang sama. Untuk menggunakan perintah ini haruslah diletakkan setelah perintah `SELECT`.

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL-Distinct.png" width="50%">

docs : <a href="https://dev.mysql.com/doc/refman/8.4/en/distinct-optimization.html"><i>https://dev.mysql.com/doc/refman/8.4/en/distinct-optimization.html</a></i>

<a id="B.1."></a>
## <b>B.1. <span style='color:#0B2F9F'>Nilai Unik pada Satu Kolom Tertentu</span></b>

#### <i><b><span style='color:#55679C'>Quest</span> : Beberapa kali DQPizza mengalami komplain, sebutkan apa saja komplain yang pernah terjadi di DQPizza!</b></i>

In [36]:
%%bigquery --project {project_id} --verbose

-- Tampilkan komplain apa saja yang pernah terjadi di DQPizza
SELECT DISTINCT complain_detail FROM dqlab-putri512.dq_pizza.orders

Executing query with job ID: 5bcc2f37-9a9e-49e9-8c5f-595d057ee1f3
Query executing: 0.52s
Job ID 5bcc2f37-9a9e-49e9-8c5f-595d057ee1f3 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

         complain_detail
0                   None
1      Dough undercooked
2      Drink was missing
3       Missing toppings
4    Order took too long
5        Pizza was burnt
6   Received wrong pizza
7  Rude staff at counter
8       Wrong pizza size

<a id="B.2."></a>
## <b>B.2. <span style='color:#0B2F9F'>Nilai Unik pada Lebih dari Satu Kolom</span></b>

Perintah `DISTINCT` dapat diterapkan dilebih dari satu kolom. Jika diterapkan pada lebih dari satu kolom maka akan menghasilkan kombinasi unik antar baris pada kolom yang terpilih

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan siapa saja karyawan yang pernah menerima komplain dan jenis komplain apa saja yang pernah terjadi!</b></i>

In [37]:
%%bigquery --project {project_id} --verbose

-- Tampilkan siapa saja karyawan yang pernah menerima komplain dan
-- jenis komplain apa saja yang pernah terjadi di DQPizza
SELECT DISTINCT
  order_maker_id,
  complain_detail
FROM dqlab-putri512.dq_pizza.orders

Executing query with job ID: dcb73c59-6975-40a5-b65a-66226425a153
Query executing: 0.49s
Job ID dcb73c59-6975-40a5-b65a-66226425a153 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

   order_maker_id   complain_detail
0       EMP000208              None
1       EMP000231              None
2       EMP000286              None
3       EMP000295              None
4       EMP000302              None
..            ...               ...
85      EMP000437  Wrong pizza size
86      EMP000560  Wrong pizza size
87      EMP000646  Wrong pizza size
88      EMP000665  Wrong pizza size
89      EMP000756  Wrong pizza size

[90 rows x 2 columns]

<a id="C"></a>
# <b>C. <span style='color:#E1B12D'><code>LIMIT</code></span></b>

Tidak semua data ingin ditampilkan untuk proses <i>sampling</i>, sehingga perlu dikontrol dan melakukan pembatasan jumlah baris yang dikembalikan oleh sebuah query.
Perintah `LIMIT <jumlah_data>` dalam SQL digunakan untuk membatasi data yang ingin ditampilkan. `LIMIT` diletakkan paling akhir dari sebuah query dengan perintah `SELECT`.

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL-Limit.png" width="50%">

docs : <a href="https://dev.mysql.com/doc/refman/8.4/en/limit-optimization.html"><i>https://dev.mysql.com/doc/refman/8.4/en/limit-optimization.html</a></i>

<a id="C.1."></a>
## <b>C.1. <span style='color:#0B2F9F'>Membatasi Jumlah Baris (yang ditampilkan) di Semua Kolom pada Data</span></b>

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan semua 5 data teratas pada tabel orders!</b></i>

In [38]:
%%bigquery --project {project_id} --verbose

-- Tampilkan semua 5 data pada tabel orders
SELECT * FROM dqlab-putri512.dq_pizza.orders
LIMIT 5

Executing query with job ID: f2e032aa-12c1-4ba7-8eb9-4823f4acaeae
Query executing: 0.49s
Job ID f2e032aa-12c1-4ba7-8eb9-4823f4acaeae successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail
0,TRX000026,CUST006333,EMP000208,01/01/2024,14:54:26,15:23:02,0,None
1,TRX000037,CUST003319,EMP000208,01/01/2024,16:56:09,17:18:48,0,None
2,TRX000057,CUST008422,EMP000208,01/01/2024,19:10:51,19:30:38,0,None
3,TRX000077,CUST001979,EMP000208,01/02/2024,12:22:46,12:41:29,0,None
4,TRX000087,CUST004837,EMP000208,01/02/2024,14:01:02,14:29:46,0,None

<a id="C.2."></a>
## <b>C.2. <span style='color:#0B2F9F'>Membatasi Jumlah Baris (yang ditampilkan) di Kolom Tertentu pada Data</span></b>

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan 7 data teratas untuk kolom order_id, customer_id, dan order_date pada tabel orders!</b></i>

In [39]:
%%bigquery --project {project_id} --verbose

-- Tampilkan 7 data teratas saja untuk kolom order_id, customer_id dan order_date
SELECT
  order_id,
  customer_id,
  order_date
FROM dqlab-putri512.dq_pizza.orders
LIMIT 7

Executing query with job ID: de9c2f06-318b-453f-8479-a898ec55d92d
Query executing: 0.58s
Job ID de9c2f06-318b-453f-8479-a898ec55d92d successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

    order_id customer_id  order_date
0  TRX000026  CUST006333  01/01/2024
1  TRX000037  CUST003319  01/01/2024
2  TRX000057  CUST008422  01/01/2024
3  TRX000077  CUST001979  01/02/2024
4  TRX000087  CUST004837  01/02/2024
5  TRX000127  CUST008782  01/02/2024
6  TRX000133  CUST005109  01/02/2024

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan 5 data saja pada kolom order_id, customer_id, order_date dan is_complain pada tabel orders namun ubah penamaan is_complain pada output menjadi is_customer_complain agar lebih jelas</b></i>

In [40]:
%%bigquery --project {project_id} --verbose

-- Tampilkan 5 data teratas saja untuk kolom order_id, customer_id, order_date dan is_complain pada tabel orders
-- namun ubah penamaan is_complain pada output menjadi is_customer_complain
SELECT
  order_id,
  customer_id,
  order_date,
  is_complain AS is_customer_complain
FROM dqlab-putri512.dq_pizza.orders
LIMIT 5

Executing query with job ID: 9dbf2661-d3ee-4fb0-91fa-d95185507a23
Query executing: 0.51s
Job ID 9dbf2661-d3ee-4fb0-91fa-d95185507a23 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

    order_id customer_id  order_date  is_customer_complain
0  TRX000026  CUST006333  01/01/2024                     0
1  TRX000037  CUST003319  01/01/2024                     0
2  TRX000057  CUST008422  01/01/2024                     0
3  TRX000077  CUST001979  01/02/2024                     0
4  TRX000087  CUST004837  01/02/2024                     0

<a id="D"></a>
# <b>D. <span style='color:#E1B12D'><code>ORDER BY</code></span></b>

Perintah lain yang tak kalah penting yang membantu dalam menganalisis data untuk melihat data dalam urutan yang diinginkan adalah perintah `ORDER BY`. Perintah `ORDER BY` dalam SQL digunakan untuk mengurutkan hasil query berdasarkan satu atau lebih kolom. Cara pengurutan data dibagi menjadi dua cara yakni <b>Ascending</b> dan <b>Descending</b>
<ul>
    <li><b>Ascending</b> : Pengurutan secara naik (dari kecil ke besar) atau A-Z</li>
    <li><b>Descending</b> : Pengurutan secara turun (dari besar ke kecil) atau Z-A</li>
</ul>

Untuk dapat menampilkan isi data secara terurut pada kolom tertentu pada sebuah tabel, eksekusi perintah


<i>docs : <a href="https://dev.mysql.com/doc/refman/8.4/en/sorting-rows.html">https://dev.mysql.com/doc/refman/8.4/en/sorting-rows.html</a></i>

<a id="D.1."></a>
## <b>D.1. <span style='color:#0B2F9F'>Mengurutkan secara <i>Ascending</i></span></b>

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL-OrderByASC.png" width="50%">

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan semua data pada tabel orders namun urutkan berdasarkan kolom order_id secara ascending!</b></i>

In [41]:
%%bigquery --project {project_id} --verbose

-- Tampilkan semua data pada tabel orders terurut berdasarkan kolom order_id secara ascending
SELECT * FROM dqlab-putri512.dq_pizza.orders
ORDER BY order_id ASC

Executing query with job ID: b5ef8727-e278-4774-b865-bde32f248b9b
Query executing: 1.30s
Job ID b5ef8727-e278-4774-b865-bde32f248b9b successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail
0,TRX000001,CUST007150,EMP000286,01/01/2024,11:38:36,12:03:29,0,None
1,TRX000002,CUST003319,EMP000646,01/01/2024,11:57:40,12:09:32,0,None
2,TRX000003,CUST001979,EMP000437,01/01/2024,12:12:28,12:38:02,1,Missing toppings
3,TRX000004,CUST007254,EMP000302,01/01/2024,12:16:31,12:32:46,1,Missing toppings
4,TRX000005,CUST004392,EMP000231,01/01/2024,12:21:30,12:33:05,0,None
...,...,...,...,...,...,...,...,...
21345,TRX021346,CUST005584,EMP000560,12/31/2024,20:51:07,21:20:56,0,None
21346,TRX021347,CUST003549,EMP000302,12/31/2024,21:14:37,21:30:28,0,None
21347,TRX021348,CUST007931,EMP000437,12/31/2024,21:23:10,21:47:34,0,None
21348,TRX021349,CUST004212,EMP000231,12/31/2024,22:09:54,22:29:02,0,None
21349,TRX021350,CUST002637,EMP000665,12/31/2024,23:02:05,23:18:55,0,None

<a id="D.2."></a>
## <b>D.2. <span style='color:#0B2F9F'>Mengurutkan secara <i>Descending</i></span></b>

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL-OrderByDESC.png" width="50%">

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan semua data pada tabel orders namun urutkan berdasarkan kolom order_date secara descending!</b></i>

In [42]:
%%bigquery --project {project_id} --verbose

-- Tampilkan semua data pada tabel orders terurut berdasarkan kolom order_date secara descending
SELECT * FROM dqlab-putri512.dq_pizza.orders
ORDER BY order_date DESC

Executing query with job ID: de762ef9-94d6-4b2f-8116-ada4e84002fd
Query executing: 1.38s
Job ID de762ef9-94d6-4b2f-8116-ada4e84002fd successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail
0,TRX021329,CUST004934,EMP000665,12/31/2024,18:52:10,19:07:29,0,None
1,TRX021332,CUST006821,EMP000286,12/31/2024,19:06:29,19:35:03,1,Order took too long
2,TRX021282,CUST007854,EMP000286,12/31/2024,12:09:59,12:24:40,0,None
3,TRX021343,CUST009740,EMP000208,12/31/2024,20:27:23,20:46:24,0,None
4,TRX021324,CUST002945,EMP000208,12/31/2024,18:36:06,18:51:40,0,None
...,...,...,...,...,...,...,...,...
21345,TRX000010,CUST007931,EMP000437,01/01/2024,13:00:15,13:14:11,0,None
21346,TRX000006,CUST002637,EMP000437,01/01/2024,12:29:36,12:51:58,0,None
21347,TRX000057,CUST008422,EMP000208,01/01/2024,19:10:51,19:30:38,0,None
21348,TRX000037,CUST003319,EMP000208,01/01/2024,16:56:09,17:18:48,0,None
21349,TRX000032,CUST001704,EMP000756,01/01/2024,15:53:18,16:16:43,0,None

<a id="D.3."></a>
## <b>D.3. <span style='color:#0B2F9F'>Kombinasi <i>Ascending</i> & <i>Descending</i> saat Mengurutkan Data</span></b>

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan siapa saja karyawan yang pernah menerima komplain dan jenis komplain apa saja yang pernah terjadi, urutkan berdasarkan jenis komplainnya secara descending dan kode pegawai secara ascending!</b></i>

In [43]:
%%bigquery --project {project_id} --verbose

-- Tampilkan siapa saja karyawan yang pernah menerima komplain dan jenis komplain apa saja yang pernah terjadi
-- urutkan berdasarkan jenis komplainnya secara descending dan kode pegawai secara ascending
SELECT DISTINCT
order_maker_id,
complain_detail
FROM dqlab-putri512.dq_pizza.orders
ORDER BY
complain_detail DESC,
order_maker_id ASC

Executing query with job ID: abb9e67a-ed6f-402e-b5c7-dc0cd5e354c0
Query executing: 0.44s
Job ID abb9e67a-ed6f-402e-b5c7-dc0cd5e354c0 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

   order_maker_id   complain_detail
0       EMP000208  Wrong pizza size
1       EMP000231  Wrong pizza size
2       EMP000286  Wrong pizza size
3       EMP000295  Wrong pizza size
4       EMP000302  Wrong pizza size
..            ...               ...
85      EMP000437              None
86      EMP000560              None
87      EMP000646              None
88      EMP000665              None
89      EMP000756              None

[90 rows x 2 columns]

Data Source : <i>https://mavenanalytics.io/challenges/maven-pizza-challenge</i> (dengan modifikasi)


---

<br>
<a href="https://www.linkedin.com/in/putri-hasinatuzzafira/"><img src="https://img.shields.io/badge/-© 2025 Putri Hasinatuzzafira-417DAC?style=for-the-badge&logoColor=white"/></a>

<a href="https://dqlab.id/"><img src="https://dqlab.id/files/dqlab/cache/87e30118ebba5ec7d96f6ea8c9dcc10b_x_118_X_55.png" align="left" /></a>